### PR TITLE
New: Add update archive and switch to nextjs react

### PR DESCRIPTION
**Pull request by Geczy**
Bye bye svelte

Also adds all media formats in telegram

Requires new environment variables, see `.env.example`

### CODE REVIEW

**Comment by RusseII** [comment]
Amazing. This adds breaking changes if I merge - correct? 

Would I have to kick all users and have them rejoin the bot? (Could just kick every1 and have them join your version of the bot)

**Comment by Geczy** [comment]
You don't have to kick anyone, it will start a new database on its own under 'users' instead of 'groups'

So they will have to just /subscribe again. And new environment variables .env.example

Yeah you could just have them join stood_bot

**Comment by Geczy** [comment]
Oh also the crontab needs updated to include ?key=x to each URL , see readme

**Comment by RusseII** [comment]
> Oh also the crontab needs updated to include ?key=x to each URL , see readme

I don't see that in readme but I assume it's just adding ?key={telegram_api_key} as query parameter

**Comment by Geczy** [comment]
> > Oh also the crontab needs updated to include ?key=x to each URL , see readme
> 
> I don't see that in readme but I assume it's just adding ?key={telegram_api_key} as query parameter

yeah , just ctrl f ?key

**Pull request merged**
